common_utils_yum:
  - lftp
  - acpid
  - atop
  - autoconf
  - automake
  - bash-completion
  - bc
  - bind-utils
  - curl
  - dmidecode
  - dstat
  - ethtool
  - fuse-sshfs
  - gcc
  - gcc-c++
  - gdisk
  - git
  - git-core
  - htop
  - iftop
  - iperf
  - ipmitool
  - jq
  - lsof
  - make
  - man
  - mc
  - mtr
  - nano
  - nc
  - ncdu
  - net-tools
  - ntp
  - numactl
  - pciutils
  - pigz
  - psmisc
  - pv
  - screen
  - smartmontools
  - strace
  - sysstat
  - tcpdump
  - telnet
  - tmux
  - usbutils
  - vim
  - wget
  - jwhois
  - yum-utils
  - lsyncd
  - opendkim
  - zlib-devel
  - zlib
  - pwgen
  - zsh
  - python-GeoIP
  - GeoIP-devel
  - GeoIP
