---
- name: Instaling ansible apt reqs...
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
  - python-pip
  - python-dev
  when: ansible_distribution == "Debian"

- name: Installing EPEL repo...
  yum: name=epel-release state=installed
  when: ansible_os_family == "RedHat"


- name: Instaling yum plugins...
  yum: name=yum-axelget state=installed update_cache=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Installing Playbook YUM deps...
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
  - libselinux-python
  - python-devel
  - python-pip
  - pyOpenSSL
  when: ansible_os_family == "RedHat"

- name: Ensure /var/www exist...
  file: state=directory dest=/var/www mode=0755
  tags:
  - mkdir-www

